### ISSUE TITLE
MCDJ Fail to load in minecraft 1.16.3

### ISSUE THREAD

**Issue by Decycle** [Shoxie12/MCDJ#9]
MCDJ fails to load in Minecraft 1.16.3
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/17/20 1:07 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:418) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.3.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.3-34.1.42.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_242] {}
-- MOD mcdj --
Details:
	Mod File: MCDJ-1.16.2-1.16.3-2.1.jar
	Failure message: MCDJ (mcdj) has failed to load correctly
		java.util.ConcurrentModificationException: null
	Mod Version: 2.1
	Mod Issue URL: https://github.com/Shoxie12/MCDJ/issues
	Exception message: java.util.ConcurrentModificationException
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_242] {}
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_242] {}
	at net.minecraft.resources.ResourcePackList.func_232624_g_(ResourcePackList.java:42) ~[?:?] {re:classloading}
	at net.minecraft.resources.ResourcePackList.func_198983_a(ResourcePackList.java:35) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_213237_g(Minecraft.java:723) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.shoxie.mcdj.proxy.ClientProxy.rpreload(ClientProxy.java:57) ~[mcdj:1.16.2-2.1] {re:classloading}
	at com.shoxie.mcdj.proxy.ClientProxy.rpinit(ClientProxy.java:52) ~[mcdj:1.16.2-2.1] {re:classloading}
	at com.shoxie.mcdj.mcdj.MusicScan(mcdj.java:154) ~[mcdj:1.16.2-2.1] {re:classloading}
	at com.shoxie.mcdj.mcdj.<init>(mcdj.java:87) ~[mcdj:1.16.2-2.1] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:34.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_242] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_242] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_242] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_242] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_242] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_242] {}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 363468976 bytes (346 MB) / 2459435008 bytes (2345 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 12
	JVM Flags: 3 total; -Xmx6144m -Xms6144m -Xms256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.42.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.42
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.42-client.jar                   |Minecraft                     |minecraft                     |1.16.3              |CREATE_REG|NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |CREATE_REG|NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |CREATE_REG|NOSIGNATURE
		flatbedrock-1.16.3-1.1.3.jar                      |Flat Bedrock                  |flatbedrock                   |1.16.3-1.1.3        |CREATE_REG|NOSIGNATURE
		CreativeCore_v2.0.10_mc1.16.4.jar                 |CreativeCore                  |creativecore                  |2.0.0               |CREATE_REG|NOSIGNATURE
		skinned_lanterns-1.16.3-1.3.0.jar                 |Skinned Lanterns              |skinnedlanterns               |1.16.3-1.3.0        |CREATE_REG|NOSIGNATURE
		jei-1.16.3-7.6.0.51.jar                           |Just Enough Items             |jei                           |7.6.0.50            |CREATE_REG|NOSIGNATURE
		Jellyfishing-1.4.0.jar                            |Jellyfishing                  |jellyfishing                  |1.4.0               |CREATE_REG|NOSIGNATURE
		ContentTweaker-1.16-1.0.0.develop.9.jar           |ContentTweaker                |contenttweaker                |1.0.0.develop.9     |CREATE_REG|NOSIGNATURE
		findme-1.16.3-2.1.0.0.jar                         |Find Me                       |findme                        |NONE                |CREATE_REG|NOSIGNATURE
		curios-forge-1.16.4-4.0.3.0.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.0      |CREATE_REG|NOSIGNATURE
		BetterCaves-1.16.3-1.0.6.jar                      |YUNG's Better Caves           |bettercaves                   |1.16.3-1.0.6        |CREATE_REG|NOSIGNATURE
		Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |CREATE_REG|NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.0.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |CREATE_REG|NOSIGNATURE
		CookingForBlockheads_1.16.3-9.2.2.jar             |Cooking for Blockheads        |cookingforblockheads          |9.2.2               |CREATE_REG|NOSIGNATURE
		ReAuth-1.16-Forge-3.9.3.jar                       |ReAuth                        |reauth                        |3.9.3               |CREATE_REG|3d:06:1e:e5:da:e2:ff:ae:04:00:be:45:5b:ff:fd:70:65:00:67:0b:33:87:a6:5f:af:20:3c:b6:a1:35:ca:7e
		Placebo-1.16.3-4.3.3.jar                          |Placebo                       |placebo                       |4.3.3               |CREATE_REG|NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |CREATE_REG|NOSIGNATURE
		Artifacts-1.16.4-2.7.1.jar                        |Artifacts                     |artifacts                     |1.16.4-2.7.1        |CREATE_REG|NOSIGNATURE
		ftb-gui-library-1604.1.1.26.jar                   |FTB GUI Library               |ftbguilibrary                 |1604.1.1.26         |CREATE_REG|NOSIGNATURE
		champions-forge-1.16.3-2.0.0.1.jar                |Champions                     |champions                     |1.16.3-2.0.0.1      |CREATE_REG|NOSIGNATURE
		Bookshelf-1.16.3-8.7.20.jar                       |Bookshelf                     |bookshelf                     |8.7.20              |CREATE_REG|NOSIGNATURE
		EnchantmentDescriptions-1.16.3-5.0.1.jar          |EnchantmentDescriptions       |enchdesc                      |5.0.1               |CREATE_REG|NOSIGNATURE
		solcarrot-1.16.3-1.9.8.jar                        |Spice of Life: Carrot Edition |solcarrot                     |1.16.3-1.9.8        |CREATE_REG|NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |CREATE_REG|NOSIGNATURE
		MCDJ-1.16.2-1.16.3-2.1.jar                        |MCDJ                          |mcdj                          |2.1                 |ERROR     |NOSIGNATURE
		JEITweaker-1.16.3-1.0.1.4.jar                     |JEI Tweaker                   |jeitweaker                    |1.0.1.4             |CREATE_REG|NOSIGNATURE
		JustEnoughResources-1.16.3-0.12.0.100.jar         |Just Enough Resources         |jeresources                   |0.12.0.100          |CREATE_REG|NOSIGNATURE
		CraftTweaker-1.16.3-7.0.0.48.jar                  |CraftTweaker                  |crafttweaker                  |7.0.0.48            |CREATE_REG|NOSIGNATURE
		forgemod_VoxelMap-1.10.11_for_1.16.3.jar          |VoxelMap                      |voxelmap                      |1.10.11             |CREATE_REG|NOSIGNATURE
		charm-forge-1.16.4-2.1.1-hotfix3.jar              |Charm                         |charm                         |2.1.1               |CREATE_REG|NOSIGNATURE
		forge-1.16.3-34.1.42-universal.jar                |Forge                         |forge                         |34.1.42             |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-277.jar                                |Quark                         |quark                         |r2.4-277            |CREATE_REG|NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |CREATE_REG|NOSIGNATURE
		dcintegration-2.0.2-1.16.jar                      |Discord Integration           |dcintegration                 |2.0.2               |CREATE_REG|NOSIGNATURE
		supplementaries-0.9.9.jar                         |Supplementaries               |supplementaries               |0.9.9               |CREATE_REG|NOSIGNATURE
		BetterMineshafts-Forge-1.16.3-1.1.jar             |YUNG's Better Mineshafts      |bettermineshafts              |1.16.3-1.1          |CREATE_REG|NOSIGNATURE
		OpenLoader-1.16.3-7.0.3.jar                       |OpenLoader                    |openloader                    |7.0.3               |CREATE_REG|NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |CREATE_REG|NOSIGNATURE
		BetterAdvancements-1.16.3-0.1.0.102.jar           |Better Advancements           |betteradvancements            |0.1.0.102           |CREATE_REG|NOSIGNATURE
	Crash Report UUID: e56af4a7-d4bb-428d-864e-79826c1671b8
	OptiFine Version: OptiFine_1.16.3_HD_U_G5
	OptiFine Build: 20201106-202857
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 ATI-4.0.47
	OpenGlRenderer: AMD Radeon Pro 560X OpenGL Engine
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12
```

**Comment by Decycle** [comment]
The problems seemed to be fixed in the latest version
